name: Build and Test Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install PyBind11
        run: pip install pybind11

      - name: Install system dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev libsqlite3-dev

      - name: Install system dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install postgresql@12
          brew install sqlite3

      - name: Install system dependencies
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install postgresql --params '/Password:password'
          choco install sqlite

      - uses: pypa/cibuildwheel@v2.17
        env:
          CIBW_ENVIRONMENT_LINUX: CXXFLAGS=-fPIC CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib
          CIBW_ARCHS_MACOS: auto universal2

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
