name: Build and Test Wheels

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PyBind11
      run: pip install pybind11

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.11.0

      - name: Install system dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev libsqlite3-dev

      - name: Install system dependencies
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install postgresql@12
          brew install sqlite3

      - name: Install system dependencies
        if: startsWith(matrix.os, 'windows')
        run: |
          choco install postgresql --params '/Password:password'
          choco install sqlite

      - name: Configure build environment
        run: |
          echo "CIBW_ENVIRONMENT='CXXFLAGS=-fPIC CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib'" >> $GITHUB_ENV

      - name: Build wheels
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl
